{% set name = "metaflow" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a82861a9cdfc9142f239a141034b06a4e38779959303d85d28977115e1622bb2

build:
  number: 0
  noarch: python
  entry_points:
    - metaflow=metaflow.main_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - boto3
    - click >=7.0
    - requests
    - setuptools
    - pylint <2.5.0

test:
  imports:
    - metaflow
    - metaflow.client
    - metaflow.datastore
    - metaflow.datastore.util
    - metaflow.datatools
    - metaflow.metadata
    - metaflow.plugins
    - metaflow.plugins.aws
    - metaflow.plugins.aws.batch
    - metaflow.plugins.conda
  commands:
    - metaflow --help

about:
  home: https://metaflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Metaflow: More Data Science, Less Engineering'
  doc_url: https://docs.metaflow.org/
  dev_url: https://github.com/Netflix/metaflow

extra:
  recipe-maintainers:
    - xhochy
    - savingoyal
