{% set name = "metaflow" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab287e0f85a245a8ded8dc4bd129af857b4df22496ddc3015e42fb23d434935c

build:
  number: 0
  noarch: python
  entry_points:
    - metaflow=metaflow.main_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - boto3
    - requests
    - setuptools
    - pylint

test:
  imports:
    - metaflow
    - metaflow._vendor
    - metaflow._vendor.click
    - metaflow._vendor.v3_5
    - metaflow._vendor.v3_5.importlib_metadata
    - metaflow._vendor.v3_6
    - metaflow._vendor.v3_6.importlib_metadata
    - metaflow.client
    - metaflow.datastore
    - metaflow.datatools
    - metaflow.metadata
    - metaflow.mflog
    - metaflow.plugins
    - metaflow.plugins.argo
    - metaflow.plugins.aws
    - metaflow.plugins.aws.batch
    - metaflow.plugins.aws.step_functions
    - metaflow.plugins.cards
    - metaflow.plugins.cards.card_modules
    - metaflow.plugins.cards.card_modules.chevron
    - metaflow.plugins.conda
    - metaflow.plugins.env_escape
    - metaflow.plugins.env_escape.communication
    - metaflow.plugins.env_escape.configurations
    - metaflow.plugins.env_escape.configurations.emulate_test_lib
    - metaflow.plugins.env_escape.configurations.test_lib_impl
    - metaflow.plugins.frameworks
    - metaflow.plugins.kubernetes
    - metaflow.plugins.metadata
  commands:
    - metaflow --help
    - metaflow tutorials list

about:
  home: https://metaflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Metaflow: More Data Science, Less Engineering'
  doc_url: https://docs.metaflow.org/
  dev_url: https://github.com/Netflix/metaflow

extra:
  recipe-maintainers:
    - savingoyal
